### ISSUE TITLE
安卓9上出现的轨迹问题

### ISSUE THREAD

**Issue by ytzht** [GIVEWAYTO/TagImageView#3]
Android版本：9
手机：一加6
拖动标签时画的线会在屏幕上留下轨迹，松开手轨迹消失
就像这样： http://pic.mae.vip/1c44548ed90bed4e10ef5d1540369861756
之前没升级9是好用的，升级9之后就出现轨迹。。。

**Comment by GIVEWAYTO** [comment]
已解决
