### ISSUE TITLE
咨询问题

### ISSUE THREAD

**Issue by zhouclcode** [GIVEWAYTO/TagImageView#5]
有没有推荐的一套类小红书图片编辑的sdk

**Comment by GIVEWAYTO** [comment]
涂图的sdk很烂 建议不要使用
我有收藏过一些优秀的开源库，可以参考一下：
https://github.com/Dean1990/MagicCamera
https://github.com/Skykai521/StickerCamera
https://github.com/imgly/pesdk-android-demo

**Comment by zhouclcode** [comment]
时间给的紧我也没办法，谢谢您的回答
