### ISSUE TITLE
大神，新年快樂，想問有關  'tag点的链接url' ?

### ISSUE THREAD

**Issue by uokivan** [GIVEWAYTO/TagImageView#6]
想問有關 'tag点的链接url' ,
 為何 bean.setUrl("https://github.com/");
但點後沒有發生呢？

**Comment by GIVEWAYTO** [comment]
在点击标签事件发生后有两种情况：
a.目前处于可移动状态->标签对称翻转
b.目前处于不可移动状态->会回调new TagImageView.ClickTagListener() {
            @Override
            public void click(TagInfoBean bean) {
                Toast.makeText(MainActivity.this, "标签被点击 == " + bean.getName(), Toast.LENGTH_SHORT).show();
            }
        }  
此处将会回调标签点击事件，在这里可以处理你要做的处理，例如跳转到tag的url链接。

你也可以根据需要修改点击事情，修改TagTextView的mTagGestureListener

**Comment by uokivan** [comment]
謝謝大神
