### ISSUE TITLE
长按Tag时间稍微久一点,就移动不了tag了,请问怎么处理

### ISSUE THREAD

**Issue by BoyYangyang** [GIVEWAYTO/TagImageView#7]
长按Tag时间稍微久一点,就移动不了tag了,请问怎么处理

**Comment by GIVEWAYTO** [comment]
在TagTextView中 添加代码mGestureDetector.setIsLongpressEnabled(false);   禁止长按事件，由于长按会将事件消费掉，无法触发滑动事件。

**Comment by BoyYangyang** [comment]
谢谢
