### ISSUE TITLE
标签迅速滑动时,有时标签会卡住滑不动

### ISSUE THREAD

**Issue by BoyYangyang** [GIVEWAYTO/TagImageView#8]
标签迅速滑动时,有时标签会卡住滑不动,和上次长按不动的问题相似,请问大神怎么解决

**Comment by GIVEWAYTO** [comment]
卡住不动之后，松手然后重新滑动有效吗？

**Comment by GIVEWAYTO** [comment]
我这边无法复现，这个问题会经常出现吗？把你的测试机型，Android版本号发我

**Comment by BoyYangyang** [comment]
卡住后,再松手,上次那个小图标也一直在,再次滑动后就会正常.一般都在滑动标签比较快的时候出现.并且标签比较多的时候出现的概率比较大,不是每次都出现,但是概率也挺大的,Meizu MX6,oppo等手机都有这个问题.麻烦大神帮忙看下,谢谢

**Comment by GIVEWAYTO** [comment]
可以发视频到我邮箱给我看看现象，我刚用了一台oppo A83  Android版本 7.1.1  测试  创建了60个标签  随机挑选了10个进行速滑都没有发生异常

**Comment by BoyYangyang** [comment]
视频发到您163的邮箱了,麻烦看一下

**Comment by BoyYangyang** [comment]
演示机子是Meizu MX6 android7.1.1

**Comment by Sun-of-East** [comment]
看视频是感觉 无法滑动的情况是你没有把手指放在标签的位置上   你可以验证一下。在标签view的滑动事件中 event.down  中打印log 查看自己是否按到了标签



gr201655@163.com
 
发件人： BoyYangyang
发送时间： 2019-05-13 16:00
收件人： GIVEWAYTO/TagImageView
抄送： Subscribed
主题： Re: [GIVEWAYTO/TagImageView] 标签迅速滑动时,有时标签会卡住滑不动 (#8)
演示机子是Meizu MX6 android7.1.1

**Comment by BoyYangyang** [comment]
大神,重新拍了个视频发你邮箱了,打日志发现,迅速滑动了,抬起手,响应了onDown事件,但不响应onUp事件导致删除按钮不消失
